### ISSUE TITLE
Could you make a debian directory ?

### ISSUE THREAD

**Issue by shirishag75** [anrieff/libcpuid#10]
Hi anrieff, 
could you make a debian directory ? It would be nice if we could have a debian directory so we could make .deb package out of it manually. You could look at eloader's I-Nex repo. for inspiration. See the debian directory that he has made but with one important distinction. It would be nice to have all the changelog in one place rather than have individual release changelogs as he has made for each release.

**Comment by anrieff** [comment]
Hi,
I don't have any experience in making .deb packages, or writing debian directories for that matter. However, looking at eloaders's example it seems easy enough to give it a try. I can't give you an estimate how soon though. Probably within the next 2 weeks, but I don't promise anything.

**Comment by gdbdzgd** [comment]
I have done this on pull request #11, could you merge this request? it tested on Debian Jessie

**Comment by shirishag75** [comment]
@gdbdzgd I am not a developer but would like to try your pull request, how do I pull your pull request ? I am already cloned and updated to the latest master.

**Comment by anrieff** [comment]
Shirish, you can test the proposed pull request by pulling gdbdzgd's github repo.

**Comment by shirishag75** [comment]
Just saw https://github.com/anrieff/libcpuid/pull/11 so have decided to wait till you pull it and add the placeholder info that is required therein. 

@gdbdzgd  I am guessing you used debhelper to create the /debian directory ?

**Comment by gdbdzgd** [comment]
@shirishag75 Debian has tool create Debian derectory  such as dh-make debmake , I use dh-make create this directory , youcan  create this reference Debian maintainer manual

**Comment by anrieff** [comment]
Issue resolved in 3bcb21a, thanks to @gdbdzgd.
