### ISSUE TITLE
Porting library.

### ISSUE THREAD

**Issue by rockstar177** [anrieff/libcpuid#100]
How can I port this library to my operating system?
What needs to be done for this?

**Comment by anrieff** [comment]
Depends on what "your operating system" means and what compiler are using on it.
Libcpuid is very portable as the only OS-dependent things are the `get_total_cpus()` function and MSR handling.

**Comment by rockstar177** [comment]
So, and if you do not use the functions `get_total_cpus()` and MSR handling", you can build a static version of the library, and link to the kernel?``

**Comment by anrieff** [comment]
Yes, even though that would restrict the OS to work with x86 only, because libcpuid only supports that platform currently.

**Comment by anrieff** [comment]
Closing task, if you have further issues feel free to reopen.
