### ISSUE TITLE
Package should not use obsolete m4 macros

### ISSUE THREAD

**Issue by martinkg** [anrieff/libcpuid#101]
I' am working on a rpm package of licpuid, the Fedora Package Policies mentioned:
Package should not use obsolete m4 macros
Note: Some obsoleted macros found, see the attachment.
See: https://fedorahosted.org/FedoraReview/wiki/AutoTools

please add the following patch to git:

`diff -up libcpuid-57298c650cd3cb326d9357cdb9b9dd51d60007bb/configure.ac.fix_obsolete_m4s libcpuid-57298c650cd3cb326d9357cdb9b9dd51d60007bb/configure.ac
--- libcpuid-57298c650cd3cb326d9357cdb9b9dd51d60007bb/configure.ac.fix_obsolete_m4s	2017-05-04 14:36:19.000000000 +0200
+++ libcpuid-57298c650cd3cb326d9357cdb9b9dd51d60007bb/configure.ac	2017-10-23 15:11:43.130346420 +0200
@@ -36,7 +36,7 @@ AC_SUBST([LIBCPUID_VERSION_INFO])
 AC_PROG_CC
 m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
 AC_C_CONST
-AM_PROG_LIBTOOL
+LT_INIT
 AM_CPPFLAGS="$CPPFLAGS"
 
 AC_CHECK_HEADERS([stdint.h])`

**Comment by anrieff** [comment]
Fixed in 2f10315.
