### ISSUE TITLE
New Release version, i.e. 0.5.0

### ISSUE THREAD

**Issue by SonGokuSSJ** [anrieff/libcpuid#105]
Would be nice if you could in some time create a new "Release" version. The actual Release version v0.4.0 is from November 2016.

**Comment by X0rg** [comment]
Bump.

At least, please tag v0.4.1. There is no API breaking, only DB changes.

**Comment by anrieff** [comment]
It is not so easy, X0rg. Tag version should be matched to what the changelog, configure.ac and debian files are saying, and they all say 0.4.0. I'm in a crunch right now, but I sincerely hope to get out of it sometime after Easter to play with this project.

**Comment by SonGokuSSJ** [comment]
I do not want to make any pressure. I just want to make sure that this has not been forgotten.

**Comment by SonGokuSSJ** [comment]
Just reminding that I still would like to see a new version release tagged as exactly 1 year has passed from opening this issue. But I do not want you to rush anything. Keep the time you need, but please do not forget it.

**Comment by anrieff** [comment]
On it now :) its quite embarrassing to be so in the flow so that you just don't realize how two years flew by (Pink Floyd "Time" lyrics heard in the background).

**Comment by anrieff** [comment]
Fixed in a6123e8.

**Comment by SonGokuSSJ** [comment]
Thank you very much for creating a new release.
