### ISSUE TITLE
Build fails on Debian 9

### ISSUE THREAD

**Issue by tymophy** [anrieff/libcpuid#107]
Not a developer, might very well be doing something wrong, but nowhere I can find to ask other than this.

Debian 9, running `cd ./libcpuid && fakeroot debian/rules build && fakeroot debian/rules binary` to install

Goes well for a while, but then get several missing files, and I can't figure out if it's a missing dependency, I'm doing something wrong in the build, or if it's an actual issue.

> dh binary  --with autotools-dev
>    dh_install
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/cpu_id_t.3" (tried in "." and "debian/tmp")
> dh_install: libcpuid14-dev missing files: /usr/share/man/man3/cpu_id_t.3
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/cpu_list_t.3" (tried in "." and "debian/tmp")
> dh_install: libcpuid14-dev missing files: /usr/share/man/man3/cpu_list_t.3
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/cpu_mark_t.3" (tried in "." and "debian/tmp")
> dh_install: libcpuid14-dev missing files: /usr/share/man/man3/cpu_mark_t.3
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/cpu_raw_data_t.3" (tried in "." and "debian/tmp")
> dh_install: libcpuid14-dev missing files: /usr/share/man/man3/cpu_raw_data_t.3
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/libcpuid.3" (tried in "." and "debian/tmp")
> dh_install: libcpuid14-dev missing files: /usr/share/man/man3/libcpuid.3
> dh_install: Cannot find (any matches for) "/usr/share/man/man3/cpuid_tool.3" (tried in "." and "debian/tmp")
> dh_install: cpuidtool missing files: /usr/share/man/man3/cpuid_tool.3

**Comment by X0rg** [comment]
Is doxygen installed?
Man pages are generated only if doxygen is detected.

**Comment by tymophy** [comment]
That was the issue, doxygen not installed.  Built now.
