### ISSUE TITLE
Hints for building on NetBSD

### ISSUE THREAD

**Issue by brucelilly** [anrieff/libcpuid#108]
libcpuid-0.4.0

README says
See Readme.md

Readme.md says:
Under linux,[...]

No instructions for other OSes.

On NetBSD:

1. Install a POSIX-compatible shell such as ksh93
    (pkg_add ast-ksh || pkgin in ast-ksh)
2. export CONFIG_SHELL=/usr/pkg/bin/ksh93
    [or the path to a working shell (w/o this environment variable,
    configure and libtool use /bin/sh, and NetBSD /bin/sh does not grok "print")]
3. Follow the "Under linux"[sic] instructions. (Note: Linux, being a proper name,
    should have an initial capital letter.)
    Note: 'make clean' if rebuilding on a different architecture (e.g. i386 vs. amd64).

With those steps, libcpuid builds and cpuid_tool/cpuid_tool produces
reasonable output for most processors tested here.

**Comment by anrieff** [comment]
Many thanks, @brucelilly !
Added in aa28586.
