### ISSUE TITLE
[Proposal] Enable CI/CD

### ISSUE THREAD

**Issue by X0rg** [anrieff/libcpuid#122]
Hello,

I propose to enable continuous integration and continuous deployment for libcpuid.
[Travis CI](https://github.com/marketplace/travis-ci) seems to be a good choice for this project: it offers support for Linux, macOS and Windows.

_What are the advantages CI/CD?_
- automatically build libcpuid for each operating system
- automatically run tests
- automatically deploy assets when a new release is tagged
All of this in about **2 minutes** on Travis servers.

I have set an example of configuration file in my repository: https://github.com/X0rg/libcpuid/blob/travis/.travis.yml
And the associated build on Travis CI: https://travis-ci.com/X0rg/libcpuid/builds/104303831
For this one, I have added a new tag (v0.4.2), and assets are available on GitHub: https://github.com/X0rg/libcpuid/releases/tag/v0.4.2

_What should be done?_
In brief, install Travis CI app for this repository and create a GitHub OAuth token to allow Travis CI to deploy assets on GitHub.

But I'm confronted to an issue with Windows build: `libcpuid_vc71.sln` and `libcpuid_vc10.sln` are for older versions of Visual Studio, and Travis CI doesn't support them.
To go further, I propose to set up a cross-platform build tool, like CMake. The main advantage is CMake is preinstalled in all operating system on Travis CI, so libcpuid can be build without installing any dependency. CMake will not replace autotools nor Visual Studio project files.

What do you think about it? Is it worth it and do you agree with that?

**Comment by anrieff** [comment]
I have "Libcpuid CI" in my internal todo list; I definitely want it. My main objective is being sure that the code remains crossplatform and that we don't break compatibility inadvertently (it has happened before), and Travis CI seems great about it. Also helping with the binary releases would be cool.

As for vc71 and vc10, I think it's fine if we drop support for them. We may only {provide binaries from, test the code with} the latest VisualC that's provided with Travis. If people want to use an older VisualC, it should be up to them to compile the sources using the project files which we'll leave. So these compilers will be somewhat supported, but not actively tested against, and users will need to file bugs if they find issues when compiling from sources for these. What do you think?

**Comment by anrieff** [comment]
Also I am neutral to CMake, if it makes life much easier, then good, otherwise if Travis can be told to import and upgrade a old .sln+.vcprojx, I'd rather use that.

**Comment by X0rg** [comment]
> As for vc71 and vc10, I think it's fine if we drop support for them. We may only {provide binaries from, test the code with} the latest VisualC that's provided with Travis. If people want to use an older VisualC, it should be up to them to compile the sources using the project files which we'll leave. So these compilers will be somewhat supported, but not actively tested against, and users will need to file bugs if they find issues when compiling from sources for these. What do you think?

Yes, why not.

> Also I am neutral to CMake, if it makes life much easier, then good, otherwise if Travis can be told to import and upgrade a old .sln+.vcprojx, I'd rather use that.

Linux and macOS build successfully with Autotools: https://travis-ci.com/X0rg/libcpuid/builds/104362507/config
So yes, taking time to set CMake for Windows doesn't worth it.

I'll get a try to update .sln+.vcprojx for Microsoft Visual Studio 2017.

**Comment by X0rg** [comment]
Ok, we can pass `/p:PlatformToolset=v141` argument to `MSBuild.exe` to build libcpuid using `libcpuid_vc10.sln` solution file.

Here are the assets: https://github.com/X0rg/libcpuid/releases/tag/v0.4.6
And the configuration file: https://travis-ci.com/X0rg/libcpuid/builds/104497846/config

Any suggestions?

**Comment by anrieff** [comment]
Very cool, @X0rg . I've signed in Travis CI now, I'll replicate your setup for my repo if you don't mind :) I'll probably try adding FreeBSD to the build OSes as well (no binaries, just whether it compiles). FreeBSD seems to be [not trivial](http://erouault.blogspot.com/2016/09/running-freebsd-in-travis-ci.html), but our task is a bit simpler since the code is small.

**Comment by anrieff** [comment]
Woow, it took you 46 commits to produce this travis config file and set up everything. Initially I thought it took you a good few hours and it is more like days.
Hats off, sir, for your contributions to this tiny project!

**Comment by X0rg** [comment]
> I've signed in Travis CI now, I'll replicate your setup for my repo if you don't mind

No problem, it is made for that. :wink: 

About Travis CI, [Windows build fails if you use secrets](https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264), that is why I use the `secure` field.
So you need to create a new token in [GitHub settings](https://github.com/settings/tokens) (with public_repo, repo:status, repo_deployment) scopes, and then you can [encrypt the token](https://docs.travis-ci.com/user/encryption-keys/).
In documentation, `travis encrypt --com SOMEVAR="secretvalue"` command is used. In fact, you do not need to set a variable name, it works with `travis encrypt --com "secretvalue"`.

> I'll probably try adding FreeBSD to the build OSes as well

I have done [some tests](https://cirrus-ci.com/build/5193918583930880) with Cirrus CI before going with Travis CI. Cirrus CI offers support for FreeBSD too, but you need to call GitHub API yourself for deployment...
But you can use Cirrus CI only to test FreeBSD build if you prefer; that is what I do [with CPU-X](https://github.com/X0rg/CPU-X/blob/master/.cirrus.yml).

> Woow, it took you 46 commits to produce this travis config file and set up everything. Initially I thought it took you a good few hours and it is more like days.

Some commits are separated of few minutes. It took me a few hours, not days. Don't worry about it.

>  Hats off, sir, for your contributions to this tiny project!

You are welcome! :beers:

**Comment by X0rg** [comment]
I'm sorry if I have scarred you with these 46 commits, so I did some cleanups on my branches. Unsuccessful attempts have been removed to leave only the final configuration files.

- Travis CI:
  - Branch: https://github.com/X0rg/libcpuid/commits/travis
  - Config: https://github.com/X0rg/libcpuid/blob/travis/.travis.yml
  - Builds: https://travis-ci.com/X0rg/libcpuid
- Cirrus CI:
  - Branch: https://github.com/X0rg/libcpuid/commits/cirrus
  - Config: https://github.com/X0rg/libcpuid/blob/cirrus/.cirrus.yml
  - Builds: https://cirrus-ci.com/github/X0rg/libcpuid

Cirrus CI lacks of features and documentation at the moment, but it is the only CI App on GitHub with FreeBSD native support.

**Comment by X0rg** [comment]
@anrieff Any update about this? Do you prefer a PR?

**Comment by kreuzerkrieg** [comment]
> @anrieff Any update about this? Do you prefer a PR?

I'm trying to add this repo to vcpkg, however autoconf is quite no go. So, I'm curious if converting to cmake was a part of your effort

**Comment by X0rg** [comment]
> So, I'm curious if converting to cmake was a part of your effort

@kreuzerkrieg: No, I succeeded without. For Linux/FreeBSD/macOS, Autotools is used, while MSBuild is used for Windows build (on Travis CI).
I do not plan to add a CMakeLists.txt, but I think it is not a hard thing to do: that must generate one binary (`cpuid_tool`), one library (`libcpuid.{a,so}`), headers/configuration for pkg-config and man-pages.

**Comment by kreuzerkrieg** [comment]
Ok, will take a look at it
Thanks for the input
