### ISSUE TITLE
Is it possible to install with yum?

### ISSUE THREAD

**Issue by Leslie-Fang** [anrieff/libcpuid#128]
Is it possible to install this tools with yum or apt?
such as the cpuid tool
```
yum install cpuid
```

**Comment by X0rg** [comment]
Yes, it is possible. I think you are talking about  `cpuid_tool`.
- On Fedora, it is provided by `libcpuid-devel` package.
- On OpenSUSE, it is provided by `libcpuid-tools` package.
- On ArchLinux, it is provided by `libcpuid` package from the AUR.

On Deb-based distro, libcpuid is not officially provided, but it can be find on some PPA.

**Comment by anrieff** [comment]
I think this closes the issue :) Many thanks, @X0rg !
