### ISSUE TITLE
dpkg-gencontrol: warning: package libcpuid: unused substitution variable ${misc:Pre-Depends}

### ISSUE THREAD

**Issue by shirishag75** [anrieff/libcpuid#13]
Hi all, 
I compiled the package using fakeroot. While I'm not sure how good the build is, it at least built as can be seen at https://paste.debian.net/167722/

While building the hitch seems to be warning as shared therein.

**Comment by anrieff** [comment]
I'll install jessie RC3 to see if I can reproduce and fix this warning.

**Comment by anrieff** [comment]
Fixed in 6b38edc.
