### ISSUE TITLE
avx512vbmi

### ISSUE THREAD

**Issue by gabrielschulhof** [anrieff/libcpuid#134]
Are there plans to add support for detecting the presence of this flag?

**Comment by anrieff** [comment]
Wouldn't be a problem.

Can you help with test data? It would be good if you (or somebody) could provide a CPUID dump from a Cannon Lake, Coffee Lake or similar new CPU with these extensions, so the new code can be paired with a test.

Creating the dump is as simple as running the `cpuid_tool` with no arguments on a machine with this CPU.

**Comment by anrieff** [comment]
@gabrielschulhof - can you supply a cpuid_tool dump? I may ask elsewhere, but it would take more time.

**Comment by gabrielschulhof** [comment]
@anrieff I'm working on acquiring one.

**Comment by X0rg** [comment]
I found some Cannon Lake and Coffee Lake dumps on [InstLatx64](http://users.atw.hu/instlatx64/).
