### ISSUE TITLE
AMD Castle Peak 

### ISSUE THREAD

**Issue by eloaders** [anrieff/libcpuid#136]
I accidentally noticed that the library does not have Castle Peak processors in the database. Is it possible to add them?
I provide links that can help.

- https://en.wikichip.org/wiki/amd/cores/castle_peak
- https://github.com/InstLatx64/InstLatx64/blob/master/AuthenticAMD/AuthenticAMD0830F10_K17_CastlePeak_CPUID.txt
- https://github.com/InstLatx64/InstLatx64/blob/master/AuthenticAMD/AuthenticAMD0830F10_K17_CastlePeak_CPUID2.txt

**Comment by anrieff** [comment]
I think PR #137 was about this, can we close this issue now?

**Comment by eloaders** [comment]
yes
