### ISSUE TITLE
lintian errors checking libcpuid.deb

### ISSUE THREAD

**Issue by shirishag75** [anrieff/libcpuid#14]
Hi all, 
There are some lintian errors maybe you or somebody else can fix before we could ask Debian to take a look at it :-

    [$] lintian -v libcpuid_0.21_amd64.deb                                                                                              
    N: Using profile debian/main.
    N: Setting up lab in /tmp/temp-lintian-lab-Zftc61CeHr ...
    N: Unpacking packages in group libcpuid/0.21
    N: ----
    N: Processing binary package libcpuid (version 0.21, arch amd64) ...
    W: libcpuid: package-name-doesnt-match-sonames libcpuid11
    E: libcpuid: description-starts-with-package-name
    W: libcpuid: binary-without-manpage usr/bin/cpuid_tool
    
I can explain what the error is there. The error is saying it starts with package name. What it actually wants to say that there is no small description. Usually when you  make a package you start with a single line which tells what the package does.  Below I share why it needs to be and which file needs to change. 

    [$] dpkg -l leafpad                                                                                                                 
    
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                           Version              Architecture         Description
    +++-==============================-====================-====================-=================================================================
    ii  leafpad                        0.8.18.1-4           amd64                GTK+ based simple text editor
    

And here's the long description of the same package :-

    [$] aptitude show leafpad                                                                                                           
    
    Package: leafpad                         
    State: installed
    Automatically installed: no
    Version: 0.8.18.1-4
    Priority: optional
    Section: editors
    Maintainer: Jari Aalto <jari.aalto@cante.net>
    Architecture: amd64
    Uncompressed Size: 739 k
    Depends: libc6 (>= 2.4), libcairo2 (>= 1.2.4), libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.10.0), libpango-1.0-0 (>= 1.14.0),
             libpangocairo-1.0-0 (>= 1.14.0)
    Suggests: evince-gtk
    Description: GTK+ based simple text editor
     Leafpad is a simple GTK+ based text editor, the user interface is similar to Notepad. It aims to be lighter than GEdit and KWrite, and to be as
     useful as them.
    Homepage: http://tarot.freeshell.org/leafpad/

So as can be seen in the long description, we have the short description as well as the long description.  

The file that needs to be changed is the control file in the /debian directory which has the description. 

I will put up a pull request in sometime but if somebody gets in before that let me not stop you. The other warnings also need to be fixed as well.

**Comment by gdbdzgd** [comment]
Fix 

root@debian:/tmp/buildd/libcpuid-0.21# lintian -v  ../libcpuid11_0.21_amd64.deb 
warning: the authors of lintian do not recommend running it with root privileges!
N: Using profile debian/main.
N: Setting up lab in /tmp/temp-lintian-lab-mNlxe6EysQ ...
N: Unpacking packages in group libcpuid/0.21
N: ----
N: Processing binary package libcpuid11 (version 0.21, arch amd64) ...
W: libcpuid11: binary-without-manpage usr/bin/cpuid_tool
root@debian:/tmp/buildd/libcpuid-0.21# lintian -v  ../libcpuid11-dev_0.21_amd64.deb 
warning: the authors of lintian do not recommend running it with root privileges!
N: Using profile debian/main.
N: Setting up lab in /tmp/temp-lintian-lab-zuSzAds5Jj ...
N: Unpacking packages in group libcpuid/0.21
N: ----
N: Processing binary package libcpuid11-dev (version 0.21, arch amd64) ...

**Comment by anrieff** [comment]
Merged, made some tiny formatting changes to library description, hope they don't mess anything up.
