### ISSUE TITLE
libcpuid via vcpkg

### ISSUE THREAD

**Issue by kreuzerkrieg** [anrieff/libcpuid#140]
FYI,
libcpuid is available for use via vcpkg for linux, osx and windows for x86 and x64
the package is not available for uwp target and arm architecture

You are more than welcome to review and comment on the package
https://github.com/microsoft/vcpkg/pull/9942

**Comment by X0rg** [comment]
@kreuzerkrieg Information added to Readme.md, thank you for your contribution. :+1:
