### ISSUE TITLE
Missing detection of SHA_NI and RDSEED on AMD

### ISSUE THREAD

**Issue by XZiar** [anrieff/libcpuid#145]
Intel has the detection:
https://github.com/anrieff/libcpuid/blob/8db3b8d2d32d22437f063ce692a1b9bb15e42d18/libcpuid/recog_intel.c#L420-L434

While AMD does not have `matchtable_ebx7`.

According to [AMD Starts Linux Enablement On Next-Gen "Zen" Architecture](https://www.phoronix.com/scan.php?page=news_item&px=AMD-Zen-CPU-Znver1), AMD zen support `SHA_NI` and `RDSEED`.

CPU-Z reports `SHA`:
![image](https://user-images.githubusercontent.com/15145384/82174420-8228b680-9885-11ea-9c6a-52db80471895.png)

I will upload the cpuid_tool dump to the bugreport.

**Comment by X0rg** [comment]
And ADX too. :slightly_smiling_face:
