### ISSUE TITLE
Report TSC multiplier

### ISSUE THREAD

**Issue by dtaskoff** [anrieff/libcpuid#147]
Since most recent CPUs have different TSC, and CPU frequencies, reading the TSC multiplier is essential, in order to report an accurate frequency.

I will try to implement this change myself, but any help would be appreciated, as well!

**Comment by dtaskoff** [comment]
My bad, it seems like you're already doing this in `get_info_*_multiplier`, am I right?

**Comment by dtaskoff** [comment]
#

**Comment by anrieff** [comment]
Yes, there are two ways to read the true CPU frequency:
* `cpu_clock_by_ic()` - which does not care about TSC multipliers and all - just a busy loop with a predictable instruction throughput, so it is a real benchmark of what the CPU actually outputs;
* RDMSR approach using `get_info_*_multiplier` and `cpu_clock_by_mark()` machinery

Both are valid.
