### ISSUE TITLE
CMake build script not in 0.5.0 tarball release

### ISSUE THREAD

**Issue by madebr** [anrieff/libcpuid#148]
Hello!

The generated 0.5.0 tarball https://github.com/anrieff/libcpuid/releases/download/v0.5.0/libcpuid-0.5.0.tar.gz
does not contain the CMake build script.
This is probably caused by autotools' `make dist` not knowing about cmake.
As a workaround, the github generated release can be used.

**Comment by anrieff** [comment]
Fixed in 92475d7.
