### ISSUE TITLE
E: libcpuid11-dev: extended-description-is-empty

### ISSUE THREAD

**Issue by shirishag75** [anrieff/libcpuid#16]
Hi all, 
Ran lintian on libcpuid11-dev again and came up with the errors :-

    [$] lintian libcpuid11-dev_0.21_amd64.deb                                                                                          
    E: libcpuid11-dev: extended-description-is-empty
    W: libcpuid11-dev: wrong-section-according-to-package-name libcpuid11-dev => libdevel

checked in /libcpuid/debian/control and saw that it indeed is empty. 

    ~/games/libcpuid/debian [$] cat control
    Source: libcpuid
    Section: utils
    Priority: optional
    Maintainer: Zhang, Guodong <gdzhang@linx-info.com>
    Build-Depends: debhelper (>= 9), autotools-dev, libtool, automake, autoconf, python
    Standards-Version: 3.9.5
    Homepage: https://github.com/anrieff/libcpuid
    
    Package: libcpuid11
    Architecture: amd64 i386
    Depends: ${shlibs:Depends}, ${misc:Depends}
    Description: small C library for x86/x86_64 CPU detection and feature extraction
     For details about the programming API, please see the docs
     on the project's site (http://libcpuid.sourceforge.net/)
    
    Package: libcpuid11-dev
    Architecture: amd64 i386
    Description: develop files for libcpuid

The last line in libcpuid11-dev just gives the short description, need the long/extended description too. 

Also if possible let libpuid11-dev have the Section:libdevel as all -dev packages have, for instance :-

    [$] aptitude show iceweasel-dev                                                                            
                              
    Package: iceweasel-dev                   
    State: not installed
    Version: 31.6.0esr-1
    Priority: optional
    Section: libdevel
    Maintainer: Maintainers of Mozilla-related packages <pkg-mozilla-maintainers@lists.alioth.debian.org>
    Architecture: amd64
    Uncompressed Size: 34.4 M
    Depends: libc6 (>= 2.4), libstdc++6 (>= 4.1.1), python-ply, libnss3-dev, libnspr4-dev, iceweasel (= 31.6.0esr-1)
    Conflicts: firefox-dev, xulrunner-dev
    Description: Development files for the Gecko engine library
     This library provides an  API for XUL applications and Gecko embedders. The Gecko engine is the core of the mozilla.org applications such as Firefox, Thunderbird or SeaMonkey. 
     
     Gecko features include XPCOM, networking, DOM editing and transaction support, XBL, XUL, SVG, XSLT, XML Extras (XMLHttpRequest and DOMParser),Web Services (SOAP), accessibility support, IPC services, gtkmozembed, etc. 
     
     Install this package if you wish to embed the Gecko engine in your program or want to develop XPCOM components. 
     
     This package also provides the Xulrunner Software Development Kit in the same form as the one you may find on mozilla.org in /usr/lib/xulrunner/sdk.
    Homepage: http://wiki.mozilla.org/XUL:Lib_XUL

**Comment by anrieff** [comment]
Fixed in 2722a10.
