### ISSUE TITLE
C:\Program Files (x86)\Embarcadero\Dev-Cpp\TDM-GCC-64\x86_64-w64-mingw32\bin\ld.exe	C:\Users\user\AppData\Local\Temp\cc79calV.o:sysinfo.cpp:(.text+0x15a): undefined reference to `cpuid_present'

### ISSUE THREAD

**Issue by MrCheatEugene** [anrieff/libcpuid#161]
Hi. I am trying to compile program with libcpuid using MiniGW, but it fails with error:
C:\Program Files (x86)\Embarcadero\Dev-Cpp\TDM-GCC-64\x86_64-w64-mingw32\bin\ld.exe	C:\Users\user\AppData\Local\Temp\cc79calV.o:sysinfo.cpp:(.text+0x15a): undefined reference to `cpuid_present'

I have included libcpuid and stdio. What could be the issue?

**Comment by X0rg** [comment]
For me, it looks like the Dynamic Linker (ld) did not find libcpuid shared library.
When you include a library header, you need to link against a library too (for example `-lcpuid`).
Are you sure you set correct flags to the compiler?

**Comment by MrCheatEugene** [comment]
Yeah, I forgot to add -lcpuid flag, now it works.
Thanks.


вс, 15 мая 2022 г. в 17:39, Xorg ***@***.***>:
