### ISSUE TITLE
cpuid_tool.exe v0.6.0 doesn't work on my PC

### ISSUE THREAD

**Issue by gtopala** [anrieff/libcpuid#172]
Windows 11 22H2 x64
cpuid_tool.exe v0.5.1 generates the attached files.
cpuid_tool.exe v0.6.0 gets stuck.
The "while (set_cpu_affinity(logical_cpu)) {" loop from cpuid_main.c line 911 doesn't end.

[raw.txt](https://github.com/anrieff/libcpuid/files/9711483/raw.txt)
[report.txt](https://github.com/anrieff/libcpuid/files/9711484/report.txt)

**Comment by anrieff** [comment]
Many thanks for the report, it looks like it's a platform-specific bug. Luckily I have a similar Windows 11 22H2 install and will investigate right away!

**Comment by anrieff** [comment]
The issue reproduces on my Celeron N4020 (Gemini Lake). Indeed, 0.5.1 works, 0.6.0 hangs.

**Comment by anrieff** [comment]
@gtopala I'm pretty sure the fix works on all PCs, but if you want to test it on yours as well, you can download the CI build artifact for Win x64 from [here](https://github.com/anrieff/libcpuid/suites/8620984164/artifacts/386990706). Again, thanks for spotting this!
