### ISSUE TITLE
Library naming inconsistent between Autotools and CMake

### ISSUE THREAD

**Issue by diizzyy** [anrieff/libcpuid#174]
Not sure what's intended but...

CMake:
lib/libcpuid.so
lib/libcpuid.so.0.6.0
lib/libcpuid.so.16

Autotools:
lib/libcpuid.so
lib/libcpuid.so.16
lib/libcpuid.so.16.0.0

These should be in sync?

Best regards,
Daniel

**Comment by X0rg** [comment]
You are right: that is inconsistent.
Let's align CMake behavior on Autotools.

**Comment by diizzyy** [comment]
Thanks
