### ISSUE TITLE
v0.6.0 alder lake(hyper thread disabled) core numbers are not correct.

### ISSUE THREAD

**Issue by goodman3654** [anrieff/libcpuid#175]
OS:win11
cpu:i9-12900
hyper thread disabled in BIOS.
task manager shows 8 p-cores, 8 e-cores.
but cpuid_tool shows 4 p-cores, 8 e-cores.

screenshot:
![libcpuid](https://user-images.githubusercontent.com/10626700/197151509-97fa71cf-e79a-4863-837f-155f402f57e0.png)

[raw.txt](https://github.com/anrieff/libcpuid/files/9837180/raw.txt)
[report.txt](https://github.com/anrieff/libcpuid/files/9837184/report.txt)

**Comment by X0rg** [comment]
Yeah, thank you very much Intel for providing wrong information in CPUID... for x86 backward compatibility, I guess. `ht` flag is present and `num_smt` reported by extended topology is still `2` for P-cores even if HT is disabled in BIOS. :man_facepalming: 

I can rely on APIC ID to find if HT is really enabled or no (similar to what is done to count cache instances). I need to create a new htable for that.
