### ISSUE TITLE
x86_64 architecture level 

### ISSUE THREAD

**Issue by DimStar77** [anrieff/libcpuid#177]
More and more distros are discussing the ability to raise their baselines from x86_64 to what has been defined as [architecture levels](https://en.wikipedia.org/wiki/X86-64), e.g x86-64-v3

I think it could be a nice addition if libcpuid could match those against the current CPU(s) and report the highest supported level of the CPU(s)

**Comment by DimStar77** [comment]
It'd be nice if the flags are matched against the levels and have the relevant output so that not everybody has to parse through the provided flags and 'construct' their architecture level

**Comment by TheTumultuousUnicornOfDarkness** [comment]
The `feature_level` field in `struct cpu_id_t` reports microarchitecture levels for x86 CPUs since 959edc34e742268e875e4fce315a476f00f642df.

Example of minimal code:
```c
#include <stdio.h>
#include <libcpuid/libcpuid.h>

int main()
{
	struct cpu_id_t cpu;
	cpu_identify(NULL, &cpu);
	printf("Microarchitecture level: %s\n", cpu_feature_level_str(cpu.feature_level));
	return 0;
}
```
Of course, you can write conditions like `if (cpu.feature_level >= CPU_FEATURE_LEVEL_X86_64_V3)`.
