### ISSUE TITLE
cpuid_tool 0.6.2 does not work on osx

### ISSUE THREAD

**Issue by chenrui333** [anrieff/libcpuid#178]
👋 it looks like cpuid_tool 0.6.2 does not work on osx. 

## Reproduce
- unzip [the release artifact](https://github.com/anrieff/libcpuid/releases/download/v0.6.2/libcpuid-0.6.2-macos.zip) on a intel chip macOS machine
- `chmod +x ./bin/cpuid_tool`
- `./bin/cpuid_tool` hanging forever

relates to https://github.com/Homebrew/homebrew-core/pull/119322

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I started a macOS Catalina VM, and I can see the infinite loop: it is similar to #172.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I ran some tests on macOS: the `thread_policy_set()` function is not failing in case the logical CPU number is invalid, thus the infinite loop.
3b0a1f7e5b10efb978cea4c5cb5b727ba1ef3655 is fixing the issue on macOS.

**Comment by chenrui333** [comment]
Thanks @TheTumultuousUnicornOfDarkness for the fix!
