### ISSUE TITLE
Win64 issues

### ISSUE THREAD

**Issue by Genoil** [anrieff/libcpuid#18]
trying to build on MSVC/x64. 

- created x64 from Win32 project
- added Build customization for masm
- added masm-x64.asm to the project.
- because of that, had to move definition of exec_cpuid inside #ifdef INLINE_ASM_SUPPORTED

remaining error is:
```
unresolved external symbol busy_sse_loop referenced in function cpu_clock_by_ic	D:\work\libcpuid\cpuid_tool\libcpuid.lib(rdtsc.obj)	cpuid_tool
````

**Comment by anrieff** [comment]
Fixed in 2834683.
