### ISSUE TITLE
cpuid_get_all_raw_data() leaves CPU affinity set to a single core

### ISSUE THREAD

**Issue by enzo1982** [anrieff/libcpuid#180]
`cpuid_get_all_raw_data()` sets the CPU affinity to read the CPUID of each core, but it does not reset the affinity afterwards. Thus, applications calling `cpuid_get_all_raw_data()` will be left pegged to the last CPU core and in case of multi-threaded applications will run extremely slow.

`cpuid_get_all_raw_data()` should reset the CPU affinity to the value it was set to when calling the function. Or at the very least clear the affinity when exiting.

**Comment by enzo1982** [comment]
OK, I found that this affects Windows systems when compiling libcpuid with `_WIN32_WINNT` set to a value `< 0x601` much worse than other cases.

This is because `SetProcessAffinityMask()` is used which sets the CPU affinity for the whole process including threads created later.

In the `>= 0x601` branch and on other OS, only the affinity of the current thread is manipulated. This can be achieved for the `< 0x601` case as well by using `SetThreadAffinityMask()`.

This would mitigate the issue significantly. However, even setting the affinity mask only for the current thread could leave the thread pegged to e.g. an E-core instead of a P-core, negatively affecting performance of single-threaded programs.

**Comment by enzo1982** [comment]
I'm preparing a patch for this to fix it on all supported platforms. Should be ready in a few days.

**Comment by anrieff** [comment]
Sorry for getting back to you late. I think libcpuid should return the process/thread affinities back to where it started from after `cpuid_get_all_raw_data`. It's splendid that you are preparing a patch.
