### ISSUE TITLE
Overclock intel CPU

### ISSUE THREAD

**Issue by nikitavedre** [anrieff/libcpuid#182]
like reading minimum and maximum frequency can we set frequency for intel cpu?

**Comment by anrieff** [comment]
Operating frequency depends both on the front-side bus frequency and the CPU freq multiplier. The max FSB frequency is motherboard specific, i.e. we can't really know unless we also build a database of motherboard chipsets and their capabilities, which is out of scope for this library.

Perhaps we can do min and max multiplier, would that work for you?

**Comment by nikitavedre** [comment]
no i want to set frequency

**Comment by anrieff** [comment]
Yes, but you have to understand, that setting a specific frequency can be achieved by many ways. My memory is a bit rusty here, but let's say you have a CPU that operates on FSB of 266 MHz and a multiplier of 10x.
This gives CPU frequency of 2660 MHz.
Say you want 3000 MHz.
One way to achieve this is to increase the FSB frequency to 300 MHz. Whether the motherboard will allow this at all (not talking about stability, but is it even possible) depends on motherboard-specific details which are out of scope for libcpuid.
Another way to achieve this is by rising the CPU multiplier to 11 and increasing the FSB to 273 MHz (which gives 273×11 = 3003 MHz), which is likely doable, but again libcpuid cannot help you here.
Yet another way is to use CPU multiplier 12 and lower the FSB to to 250 MHz. There are a lot of other ways.

In any case, libcpuid can only give you the min and max multipliers, then you have to do some assumptions about how much you can tune the FSB frequency, and then you can compute which CPU frequencies are theoretically reachable for this CPU.

Hope this helps!
