### ISSUE TITLE
minimum and maximum frequency of AMD cpu

### ISSUE THREAD

**Issue by nikitavedre** [anrieff/libcpuid#183]
How to find out minimum and maximum frequency of AMD cpu?

**Comment by anrieff** [comment]
Hey, sorry for not having enough time to look in depth into this question. I'll only cover the surface of it. Generally you want to look into P-states and obtain a list of the available P-states. This is contained in MSRs if I'm not mistaken. As an inspiration, if you're on Linux, you may look into `turbostat` from kernel-tools ([source](https://github.com/torvalds/linux/blob/master/tools/power/x86/turbostat/turbostat.c)).

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> How to find out minimum and maximum frequency of AMD cpu?

You can use the `cpuid_tool --report --rdmsr` command with root privileges.
Example of output:
```
# cpuid_tool --report --rdmsr
...
--------------------------------------------------------------------------------
  MSR.mperf  : 16 MHz
  MSR.aperf  : 51 MHz
  min. multi.: 22.00
  cur. multi.: 38.00
  max. multi.: 38.00
  core volt. : 1.10 Volts
  bus clock  : 100.00 MHz
```
Frequencies are:
- minimum: `bus clock` x `min. multi.`
- maximum: `bus clock` x `max. multi.`

Please note the maximum frequency reported for AMD CPU is the base frequency, not the maximum boost frequency.

**Comment by nikitavedre** [comment]
which MSR register address is used to find min and max register address?

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> which MSR register address is used to find min and max register address?

https://github.com/anrieff/libcpuid/blob/995f7d12d97a7e7e982317eaa64efd46f8a55757/libcpuid/rdmsr.c#L561-L568
- For maximum: `MSR_PSTATE_0` register.
- For minimum: it is the latest valid P-State (for instance, `MSR_PSTATE_2` on my Ryzen 3600X).

**Comment by nikitavedre** [comment]
in which bits min and max value is saved in MSR register?

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> in which bits min and max value is saved in MSR register?

It depends of CPU model, and there is a formula to compute the multiplier. I invite you to have a look directly in the source code:
https://github.com/anrieff/libcpuid/blob/5cfff28c43f12fe9aeeaa3da94843281522ce9cc/libcpuid/rdmsr.c#L648-L763
Furthermore, this is documented by AMD: you can read BKDG or PPR (links are in the file) if you are looking for good reading material. :book:

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I am closing this issue: we answered all questions and it does not look like a libcpuid issue.
