### ISSUE TITLE
Missing `centaur_code_t.h`

### ISSUE THREAD

**Issue by Cellesti** [anrieff/libcpuid#192]
Hello, it seems the [release tarball](https://github.com/anrieff/libcpuid/releases/download/v0.6.4/libcpuid-0.6.4.tar.gz) does not have `centaur_code_t.h` included in it.

**Comment by NoviciusVulgaris** [comment]
+1, I also cannot build 0.6.4 due to this problem.

**Comment by invakid404** [comment]
We're also experiencing this issue in Funtoo Linux. We've switched to using the source tarball provided by GitHub for the time being.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Hello,

Sorry for the inconvenience. I am working on a quick fix.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Fixed by 02237e67f5cbff348c63ad5338a70d75909a23b1. I removed old artifacts with missing file, fixed release is available here: https://github.com/anrieff/libcpuid/releases/tag/v0.6.4
