### ISSUE TITLE
Does this library have some options that depend on the kernel?

### ISSUE THREAD

**Issue by chopin1998** [anrieff/libcpuid#193]
I have upgraded the kernel and after that, I am unable to get parameters such as bus frequency and CPU voltage. Does libcpuid require any special memory options to work properly?

btw, i can use rdmsr/rwmsr

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Hello @chopin1998,

Can you be more specific about your kernel? Libcpuid supports a lot of OS (Linux, FreeBSD, Windows, etc...).

Bus frequency and CPU voltage are retrieved from CPU MSRs (https://github.com/anrieff/libcpuid/blob/master/libcpuid/rdmsr.c).
A kernel module may be required (e.g. `msr` on Linux) and root privileges may be required (e.g. to read `/dev/cpu/0/msr`).

**Comment by chopin1998** [comment]
> Hello @chopin1998,
> 
> Can you be more specific about your kernel? Libcpuid supports a lot of OS (Linux, FreeBSD, Windows, etc...).
> 
> Bus frequency and CPU voltage are retrieved from CPU MSRs (https://github.com/anrieff/libcpuid/blob/master/libcpuid/rdmsr.c). A kernel module may be required (e.g. `msr` on Linux) and root privileges may be required (e.g. to read `/dev/cpu/0/msr`).

sorry, i mean linux, my kernel compiled by myself.

module "msr" included, and i can use msr-tools like

![image](https://github.com/anrieff/libcpuid/assets/643792/1aa122ae-6751-479c-b394-bd38979a7ad8)


but when i use cpu-x, it cannot read voltage/ bus speed and multiplier, etc.

![image](https://github.com/anrieff/libcpuid/assets/643792/3408a7ff-ae62-47c1-9281-0ac72a688117)

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> but when i use cpu-x, it cannot read voltage/ bus speed and multiplier, etc.

Then your issue is related to CPU-X, not libcpuid. You need to start the daemon ("Start daemon" button from the GUI), because only the daemon runs as root and can read CPU MSRs.

**Comment by chopin1998** [comment]
ok...thank you!
