### ISSUE TITLE
Idea: Link to users of libcpuid (project or using code directly)

### ISSUE THREAD

**Issue by hartwork** [anrieff/libcpuid#24]
Hi!

So far there are two users of libcpuid that I am aware of:
* CPU-X (https://github.com/X0rg/CPU-X)
* fre:ac (https://www.freac.org/)

Maybe it would be worth the effort to make a list of projects using libcpuid somewhere (unless there already is such a list, while I didn't find any).
For an example of what a rather detailed version could look like please check http://uriparser.sourceforge.net/#users .

Benefits could be both demonstrating existing adoption as well as pointing to real code using libcpuid in the wild for new users to learn from.
I won't be offended if you close the ticket as wontfix though, just an idea.

Best, S

**Comment by anrieff** [comment]
Fixed in 0f679a5.
Thank you for the idea, this is certainly good. I'll add by own projects that utilize libcpuid to that list as well.
