### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by niXman** [anrieff/libcpuid#25]
Hi,

I'm trying to build `libcpuid` for windows using MinGW-W64 compiler but get the following error:
```
rdmsr.c: In function 'cpu_rdmsr_range':
rdmsr.c:439:19: error: 'struct msr_driver_t' has no member named 'fd'
  if (pread (handle->fd, &data, sizeof data, reg) != sizeof data)
```

As I can see there is no `fd` member in struct `msr_driver_t`: https://github.com/anrieff/libcpuid/blob/master/libcpuid/rdmsr.c#L139

Ideas?

Thanks.

**Comment by anrieff** [comment]
Yeah, I committed some fixes, but they are verified against MSVC. Can you test if that resolves the compile error on your side?

**Comment by niXman** [comment]
Yes, fixed.

Thanks!
