### ISSUE TITLE
Windows Build error

### ISSUE THREAD

**Issue by Malesio** [anrieff/libcpuid#28]
Hello,

Trying to build `libcpuid` for Windows using Mingw-w64, gcc 5.2.0 but I get some errors : 

`../libcpuid/.libs/libcpuid.a(rmdsr.o): In function 'extract_driver':`
`l:\libcpuid-0.2.2\libcpuid/rdmsr.c:212: undefined reference to 'cc_x64driver_code_size'
l:\libcpuid-0.2.2\libcpuid/rdmsr.c:212: undefined reference to 'cc_x64driver_code'
l:\libcpuid-0.2.2\libcpuid/rdmsr.c:214: undefined reference to 'cc_x86driver_code_size'
l:\libcpuid-0.2.2\libcpuid/rdmsr.c:214: undefined reference to 'cc_x86driver_code'`

I've noticed that these errors are due to non declared extern variables. 
I've also seen that they're declared in `msrdriver.c`, which is never compiled, unless I've become blind.

Any ideas ?

Thanks.

**Comment by anrieff** [comment]
Fixed in 281d472.
