### ISSUE TITLE
L4 cache

### ISSUE THREAD

**Issue by wdlkmpx** [anrieff/libcpuid#40]
I wonder if there's a way get this info. I've seen this info in txt form in some cpu-z reports. Core i7 processors.

In the wiki there are some hints:
"Intel Haswell CPUs with integrated Intel Iris Pro Graphics have 128 MB of eDRAM acting essentially as an L4 cache."

It might a good idea to add 2 new members to the cpu_id_t struct:
l4_cache
l4_assoc

This info is also easy to determine in modern cpus that use model numbers (brand_str)

**Comment by anrieff** [comment]
Probably something like this: https://software.intel.com/en-us/articles/gpu-detect-sample

However, that requires DirectX, and if there's no way around it - we should be doing something else. Geekbench apparently has L4 cache detection, and they are crossplatform, so chances are it's doable.

**Comment by anrieff** [comment]
Did you have a chance to explore? We might close this if it's windows-specific or requires directX.

**Comment by wdlkmpx** [comment]
Apparently it uses many win api functions, will take a closer look

**Comment by wdlkmpx** [comment]
There is useful code, but the means to get the raw is quite obscure to me, full of win api functions, which requires learning what most functions do internally, too much for me.

I'll close for it now, perhaps @X0rg can look into the code, I see there is a __cpuid

https://msdn.microsoft.com/en-us/library/hskdteyh.aspx

**Comment by X0rg** [comment]
I have never used Win API, and my C++ level is very bad.
I'll take a look in [Intel Architectures Software Developer’s Manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf), maybe there are explanations.

**Comment by anrieff** [comment]
Actually, John from GeekBench tuned in and shared that L4 cache is a simple matter of deterministic cache decoding in CPUID leaf 04h. In hindsight, I've made `cpuid_get_raw_data()` only fetch the data for ECX=0, 1, 2 and 3 - getting us L1i, L1d, L2 and L3 - but no L4. I will update the relevant code about this soon.

**Comment by X0rg** [comment]
Do you will add `l4_cache`, `l4_assoc` and `l4_cacheline` variables in cpu_id_t?

**Comment by anrieff** [comment]
Yes. I want to have this tested first, and I am waiting for some friends which might have Crystalwell CPUs to send in some raw.txt files to test decoding. Of course, that means all tests will be invalidated soon, since they'd need those two fields.

**Comment by anrieff** [comment]
Yes. I plan to

- [ ] Add `l4_cache`, `l4_assoc` and `l4_cacheline` fields to `cpu_id_t`.
- [ ] Test L4 cache handling code.
- [ ] Add the sent raw.txt to tests, and update all other tests.
- [ ] Compile static and dynamic library versions for Win32, Win64, and Mac OS X, and make a release in Sourceforge. I believe there will be some minor changes here, since the MSVC compiler is C89 only (I'm using MSVC7.1 for best compatibility) and doesn't like declaring variables "as needed". Anyways, the fixes there will be trivial.
- [ ] Tag v0.3.0 in github.

**Comment by phprus** [comment]
@anrieff 
raw.txt for Intel Core i7-4750HQ: http://ark.intel.com/products/codename/51802/Crystal-Well#@Mobile
[raw.txt](https://github.com/anrieff/libcpuid/files/306596/raw.txt)

**Comment by anrieff** [comment]
Thank you **SO** much! I've been trying desperately to find exactly that, but none of my friends had a Crystalwell.

**Comment by phprus** [comment]
These data are obtained on MacBook Pro Retina (Mid 2014) of my friend.

**Comment by anrieff** [comment]
Well I pinged friends with Mid-2014 MacBook Pro Retinas, but they all had Broadwell-U CPUs, and no eDRAM. Anyway, the cache size is detected, I pushed

**Comment by phprus** [comment]
Win32 build errors:

1) ATOM is a predefined macro in windef.h
2) Visual studio does not support c99:
  2.1) in function cpuid_identify_intel: variables declaring "as needed"
  2.2) c99 struct initialization in file rdmsr.c: "static struct internal_id_info_t internal = { .score = -1 };"

**Comment by anrieff** [comment]
I know, I'll fix these as soon as I get back my Windows machine.

**Comment by wdlkmpx** [comment]
Last time i compiled a win32 binary with a mingw cross compiler.. it
did work.. and ran fine in... wine

**Comment by anrieff** [comment]
L4 cache fully supported in f52c02 (tests updated). The Intel Core i7-4750HQ test added in 87f305.
