### ISSUE TITLE
How to build and install doc?

### ISSUE THREAD

**Issue by X0rg** [anrieff/libcpuid#44]
Because libcpuid is a library, doc can be helpful for developers. ;)
I have tried to run `doxygen Doxyfile`, and I have a `libcpuid/docs` directory with HTML, Tex and uncompressed man pages now.
But how to install them?

Targets like `install-man`, `html-recursive` or `install-html-recursive` do noting.

**Comment by anrieff** [comment]
I haven't researched that. My approach previously was to upload the generated HTML docs to http://libcpuid.sourceforge.net/doxy/index.html
But I haven't done that since 2009 :) I'll take a note in my calendar to upload the latest version soon. Maybe in github as well.

If you like to investigate how to create the `install-man` target, go ahead, it shouldn't be hard.

**Comment by X0rg** [comment]
I'm sorry, but I'm unable to do this. I have never used automake.
I have tried [this](http://chris-miceli.blogspot.fr/2011/01/integrating-doxygen-with-autotools.html), but I think it's a bad approach.
An other way with [this](http://realmike.org/blog/2010/07/18/gnu-automake-by-example/#doxygen) or [this](http://www.gnu.org/software/autoconf-archive/ax_prog_doxygen.html), but I can't make it working.

One suggest I can do: rename Doxyfile in Doxyfile.in, and replace:
```
PROJECT_NUMBER         = 0.1
INPUT                  = ./
```
by:
```
PROJECT_NUMBER         = @PACKAGE_VERSION@
INPUT                  = @top_srcdir@/libcpuid
```
And then adding Doxyfile in `AC_CONFIG_FILES`.

**Comment by anrieff** [comment]
Thanks for the suggestions, I did them. The documentation generated from the latest sources can be found [**here**](http://libcpuid.sourceforge.net/doxy/index.html).

I'll update the Readme to reflect that.

**Comment by X0rg** [comment]
Thank for that. Do you know how to do for man pages through Automake?

**Comment by anrieff** [comment]
More work needs to be done before we get useful man pages. I just took a look into what doxygen builds - all the functions are documented in one big entry, not in separate manpages. We should fix that first (I don't know how, as I am novice on Doxygen, but Google suggests it's done by grouping). If you can give a hand at this, that would be great.

**Comment by X0rg** [comment]
Here my try: de7a6b63fab011362260bf1b4917751dbb3a2697.
But I get following errors:
```
doxygen.am:35: error: DX_COND_doc does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:41: error: DX_COND_html does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:51: error: DX_COND_chm does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:55: error: DX_COND_chi does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:67: error: DX_COND_man does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:77: error: DX_COND_rtf does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:87: error: DX_COND_xml does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:97: error: DX_COND_ps does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:126: error: DX_COND_pdf does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
doxygen.am:155: error: DX_COND_latex does not appear in AM_CONDITIONAL
Makefile.am:3:   'doxygen.am' included from here
```
I think I'll give up.

**Comment by wdlkmpx** [comment]
You said you ran ```doxy Doxyfile``` and then you have all the docs in the dir... I saw some make files before and basically this seems to be the syntax

file_that_is_missing: how_to_generate_it

this is from megatools

	%.1 %.5 %.7: %.txt docs/shared-options.txt docs/remote-paths.txt docs/footer.txt docs/asciidoc.conf
		$(AM_V_GEN)a2x --asciidoc-opts="-f docs/asciidoc.conf" -f manpage $<
		@sed -i 's/\[FIXME: manual]/Megatools Manual/' $@
		@sed -i 's/\[FIXME: source]/megatools $(VERSION)/' $@

This is my guess:

%.1 %.5 %.7: these files are missing/to generated (man pages)
%.txt docs/shared-options.txt docs/remote-paths.txt docs/footer.txt docs/asciidoc.conf : these files should be already there
$(AM_V_GEN)a2x --asciidoc-opts="-f docs/asciidoc.conf" -f manpage $<: commands to perform (not sure to what files)

So, if you say you ran ```doxygen Doxyfile```

perhaps the solution could be something like this:

*.html: doxygen Doxyfile

or perhaps:

doc1.htm doc2.html ... : doxygen Doxyfile

...just giving ideas... I never build docs, and don't have doxyfile installed

**Comment by X0rg** [comment]
`doxygen Doxyfile` is the manual command.
With doxygen.am and ax_prog_doxygen.m4 files, Autotools should be able use Doxygen.
The idea is do make doc and then install. These files add a `make doxygen-man` target, which does that.
Because I'm unfamiliar with Autotools, I don't understand what's the problem.

**Comment by wdlkmpx** [comment]
It's worth learning, it's extremely easy to cross compile, make static builds and do many things with the files generated by autotools (due the somewhat generic Makefiles it generates, the environment variables it can use, etc).. all without you having to bother to hardcode everything...

**Comment by X0rg** [comment]
Yes, sure. I have already write Makefile by myself, and I know why build automation tools are used.
When I say "I'm unfamiliar", I mean I don't use it because I dislike it (I use CMake when it's needed).
One example with CMake: bd12711d65a7c465367bf46a35b838156351136d.
The `docs` target is automatically call on `make` command. On `make install`, it installs man pages. Yes, there are uncompressed...
