### ISSUE TITLE
Propositional cleanups for cpu_msrinfo()

### ISSUE THREAD

**Issue by X0rg** [anrieff/libcpuid#46]
By my fault, the `cpu_msrinfo()` source code is unpleasant to read. Before doing something, I want your opinion.

* The first idea is standardization: `INFO_MPERF` and `INFO_APERF` use a sub-function; why not do sub-functions for others? E.g. move `INFO_CUR_MULTIPLIER` in a static function like `static double get_info_cur_multiplier()`.

* The second idea is about model specific code, actually only CPU vendor is checked, but it's unclear when registers are not the same for all models (e.g. in `INFO_CUR_MULTIPLIER`, there is both code for newer Intel CPUs and older like Pentium III). Maybe use internal codes used in detection, or something like that?

* The third idea is to try to improve existing source code in `cpu_msrinfo()`.

I close this issue, due to it is not an issue.

**Comment by anrieff** [comment]
Sorry I forgot to answer this. Standartization is a good idea. I'd even suggest we can move all MSR-decoding functionality into a separate file (decode_msr.c?). And yes, `cpu_msrinfo()` should definitely use decoding internals to decide whether some MSR is implemented and how it should be used.

**Comment by X0rg** [comment]
About use decoding internals, do you have any idea to do that?
One idea: a `cpuid_get_vendor`like function which returns XXX_code_t.
```
intel_code_t cpuid_get_intel_code(void);
amd_code_t cpuid_get_amd_code(void);
```

**Comment by anrieff** [comment]
No, that would lead to code duplication. I would propose to create a new, internal function `cpu_ident_internal`, which does much the same as the current `cpu_identify` does, but accepts a third parameter, a structure of `internal_id_info_t` which it passes along to `cpuid_identify_intel` and `cpuid_identify_intel`, so they can store the internal detection codes you could use in MSR decoding (at minimum, the structure could contain vendor, intel code, amd code, etc.). You'd call this internal function directly from `cpu_msrinfo`. The old official API function `cpu_identify` will then be just a wrapper that calls `cpu_ident_internal` and discards the internal info struct.

**Comment by X0rg** [comment]
The first step is done (77575736dd87707cfffa87f14fa789b6c7f04c60). I'll improve that.

So, if `cpu_ident_internal()` is internal, where to declare `internal_id_info_t`? Maybe in `libcpuid_util.h`.
`cpu_identify()` can not access Intel/AMD code: the brand code is given by `get_brand_code()`, but it is not stored in cpu_id_t structure.
And intel_code_t/amd_code_t can't be reached from `cpu_msrinfo()`.

**Comment by anrieff** [comment]
Your first step seems very good, well done.
On the questions, you can put all definitions (`internal_id_info_t` struct, the `intel_code_t` and `amd_code_t` enums, the way they are defined now with the includes) inside a new header, say "libcpuid_internal.h". You can also place the prototype of `cpu_ident_internal()` there. Then by including this header, you'd have everything under your disposal from cpu_msrinfo() when including that header.

Btw, if you want, I can do the changes myself. If you want, issue a pull request for the first step, so that I can merge.

**Comment by X0rg** [comment]
I think it's better you do this yourself. You know what you want, and if I do this myself, I can be wrong.

**Comment by anrieff** [comment]
Sure, on it.

**Comment by X0rg** [comment]
I'm looking for INFO_CUR_MULTIPLIER and INFO_MAX_MULTIPLIER support for AMD CPUs too.
The bus speed is not the same for all models: it depends of CPU family/model.
It seems the default bus speed is 200MHz for AMD CPUs (FX-XXXX) ans 100MHz for AMD APUs (AX-XXXX).

In fact, with CpuDid and CpuFid, we can compute CoreCOF ([table 299](http://support.amd.com/TechDocs/42301_15h_Mod_00h-0Fh_BKDG.pdf)):
> Core current operating frequency in MHz. CoreCOF = 100 * (MSRC001_00[6B:64][CpuFid] + 10h) / (2^MSRC001_00[6B:64][CpuDid]).

So, I think we can compute maximum core frequency (P-STATE 0), current core frequency (actual P-STATE) and minimum core frequency (last P-STATE). Depending of bus speed, it will give CPU multiplier.

I can't achieve that without having CPU information in `cpu_msrinfo()`.

**Comment by anrieff** [comment]
Yeah, the reorganization is almost ready (the weekend was crazy, so I didn't get much done). Will post it later today or tomorrow.

**Comment by X0rg** [comment]
Ok, thank you in advance.

**Comment by anrieff** [comment]
Done

**Comment by X0rg** [comment]
Thank you. Great job. :)

**Comment by phprus** [comment]
Hello!

Library ABI changed but soversion not changed.

According to the recommendations https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html and https://autotools.io/libtool/version.html "age" field changes only compatible changes.

If the application is linked to libcpuid.so.11 (the default), when you install libcpuid 0.3.0 application receives an ABI-incompatible libcpuid.so.11.2.0 and stop working.

If the field "age" does not change, the soversion is changed and the library will be named, for example, libcpuid.so.12. And the application will not receive an incompatible version of the library.

My English is very bad. Sorry...

P.S. Good tools to check abi compatibility: https://github.com/lvc/abi-compliance-checker

**Comment by X0rg** [comment]
Hello,

Libcpuid 0.3.0 is not tagged. Some patches are pending (I'm working on it).
It would be ready tomorrow for me.
I think @anrieff is waiting for that.

**Comment by phprus** [comment]
@X0rg, Yes is not tagged now.
But @anrieff change version-info in file configure.ac. And I think this changing version-info may cause to compatibility problems in future.

**Comment by anrieff** [comment]
@phprus thanks for the pointer. I found it strange it was producing libcpuid.so.11.2.0 and I was slightly concerned as well. It seems my "short walkthrough" in configure.ac is a bit wrong on point 1.1.

Anyway, I've pushed a fix which sets CURRENT to 13, AGE and REVISION to 0, this results in `libcpuid.so.13.0.0`, let me know if that's correct.

**Comment by phprus** [comment]
This is solving compatibility problem. New applications will be linked with the new name libcpuid.so.13.

I do not know how it is right. I have not worked with GNU Libtool and its version-info option guides earlier.

**Comment by phprus** [comment]
Warnings on OS X (commit dbf9991553b603f3b2789a3cf7457a546d9d48d4):

<pre>
rdmsr.c:540:12: warning: unused function 'rdmsr_supported' [-Wunused-function]
static int rdmsr_supported(void)
           ^
rdmsr.c:546:12: warning: unused function 'perfmsr_measure' [-Wunused-function]
static int perfmsr_measure(struct msr_driver_t* handle, int msr)
           ^
rdmsr.c:586:15: warning: unused function 'get_info_min_multiplier' [-Wunused-function]
static double get_info_min_multiplier(struct msr_driver_t* handle, struct cpu_id_t *id,
              ^
rdmsr.c:619:15: warning: unused function 'get_info_cur_multiplier' [-Wunused-function]
static double get_info_cur_multiplier(struct msr_driver_t* handle, struct cpu_id_t *id,
              ^
rdmsr.c:648:15: warning: unused function 'get_info_max_multiplier' [-Wunused-function]
static double get_info_max_multiplier(struct msr_driver_t* handle, struct cpu_id_t *id,
              ^
rdmsr.c:688:12: warning: unused function 'get_info_temperature' [-Wunused-function]
static int get_info_temperature(struct msr_driver_t* handle, struct cpu_id_t *id,
           ^
rdmsr.c:716:15: warning: unused function 'get_info_voltage' [-Wunused-function]
static double get_info_voltage(struct msr_driver_t* handle, struct cpu_id_t *id,
              ^
rdmsr.c:743:15: warning: unused function 'get_info_bus_clock' [-Wunused-function]
static double get_info_bus_clock(struct msr_driver_t* handle, struct cpu_id_t *id,
              ^
8 warnings generated.
</pre>

**Comment by anrieff** [comment]
Yes, that's because those functions aren't used, since the RDMSR* stuff isn't available on Mac OS X. I've submitted a fix which works around those warnings - thanks for the pointer.

**Comment by X0rg** [comment]
`RDMSR_UNSUPPORTED_OS` and `MSRINFO_DEFINED` macros are redundant.
Both have the same purpose, this is only the `#ifndef` on [line 508](https://github.com/anrieff/libcpuid/blob/24d7c318d076b6efc7b88e8418b8853e46f48172/libcpuid/rdmsr.c#L508) which avoid these warnings.
I think `MSRINFO_DEFINED` can be removed safely.

**Comment by anrieff** [comment]
Fixed.

**Comment by X0rg** [comment]
Thank you.
