### ISSUE TITLE
Broadwell-E not recognised properly

### ISSUE THREAD

**Issue by Groucho2004** [anrieff/libcpuid#53]
brand_str: "Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz"
cpu_codename returns: "Unknown Core 2"

**Comment by anrieff** [comment]
Please run the "cpuid_tool" utility that goes with the lib and send here the generated 'raw.txt'. The procedure is described [here](http://libcpuid.sourceforge.net/bugreport.php), you may even use the form there for the upload.

**Comment by Groucho2004** [comment]
Files attached.
[report.txt](https://github.com/anrieff/libcpuid/files/433539/report.txt)
[raw.txt](https://github.com/anrieff/libcpuid/files/433540/raw.txt)

**Comment by Groucho2004** [comment]
CPUID is present
CPU Info:
------------------
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz'
  family     : 6 (06h)
  model      : 15 (0Fh)
  stepping   : 1 (01h)
  ext_family : 6 (06h)
  ext_model  : 79 (4Fh)
  num_cores  : 10
  num_logical: 20
  tot_logical: 20
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 256 KB
  L3 cache   : 25600 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L2 assoc.  : 8-way
  L3 assoc.  : 20-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  SSE units  : 128 bits (non-authoritative)
  code name  : `Unknown Core 2'
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni pclmul dts64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 syscall xd movbe popcnt aes xsave osxsave avx rdtscp lm lahf_lm constant_tsc fma3 f16c rdrand x2apic avx2 bmi1 bmi2 hle rtm
version=0.3.0
basic_cpuid[0]=00000014 756e6547 6c65746e 49656e69
basic_cpuid[1]=000406f1 04200800 7ffefbbf bfebfbff
basic_cpuid[2]=76036301 00f0b5ff 00000000 00c30000
basic_cpuid[3]=00000000 00000000 00000000 00000000
basic_cpuid[4]=3c004121 01c0003f 0000003f 00000000
basic_cpuid[5]=00000040 00000040 00000003 00002120
basic_cpuid[6]=00000077 00000002 00000009 00000000
basic_cpuid[7]=00000000 021cbfbb 00000000 00000000
basic_cpuid[8]=00000000 00000000 00000000 00000000
basic_cpuid[9]=00000001 00000000 00000000 00000000
basic_cpuid[10]=07300403 00000000 00000000 00000603
basic_cpuid[11]=00000001 00000002 00000100 00000004
basic_cpuid[12]=00000000 00000000 00000000 00000000
basic_cpuid[13]=00000007 00000340 00000340 00000000
basic_cpuid[14]=00000000 00000000 00000000 00000000
basic_cpuid[15]=00000000 0000004f 00000000 00000002
basic_cpuid[16]=00000000 00000002 00000000 00000000
basic_cpuid[17]=00000000 00000000 00000000 00000000
basic_cpuid[18]=00000000 00000000 00000000 00000000
basic_cpuid[19]=00000000 00000000 00000000 00000000
basic_cpuid[20]=00000000 00000001 00000001 00000000
basic_cpuid[21]=00000000 00000001 00000001 00000000
basic_cpuid[22]=00000000 00000001 00000001 00000000
basic_cpuid[23]=00000000 00000001 00000001 00000000
basic_cpuid[24]=00000000 00000001 00000001 00000000
basic_cpuid[25]=00000000 00000001 00000001 00000000
basic_cpuid[26]=00000000 00000001 00000001 00000000
basic_cpuid[27]=00000000 00000001 00000001 00000000
basic_cpuid[28]=00000000 00000001 00000001 00000000
basic_cpuid[29]=00000000 00000001 00000001 00000000
basic_cpuid[30]=00000000 00000001 00000001 00000000
basic_cpuid[31]=00000000 00000001 00000001 00000000
ext_cpuid[0]=80000008 00000000 00000000 00000000
ext_cpuid[1]=00000000 00000000 00000121 2c100800
ext_cpuid[2]=65746e49 2952286c 726f4320 4d542865
ext_cpuid[3]=37692029 3539362d 43205830 40205550
ext_cpuid[4]=302e3320 7a484730 00000000 00000000
ext_cpuid[5]=00000000 00000000 00000000 00000000
ext_cpuid[6]=00000000 00000000 01006040 00000000
ext_cpuid[7]=00000000 00000000 00000000 00000100
ext_cpuid[8]=0000302e 00000000 00000000 00000000
ext_cpuid[9]=00000000 00000001 00000001 00000000
ext_cpuid[10]=00000000 00000001 00000001 00000000
ext_cpuid[11]=00000000 00000001 00000001 00000000
ext_cpuid[12]=00000000 00000001 00000001 00000000
ext_cpuid[13]=00000000 00000001 00000001 00000000
ext_cpuid[14]=00000000 00000001 00000001 00000000
ext_cpuid[15]=00000000 00000001 00000001 00000000
ext_cpuid[16]=00000000 00000001 00000001 00000000
ext_cpuid[17]=00000000 00000001 00000001 00000000
ext_cpuid[18]=00000000 00000001 00000001 00000000
ext_cpuid[19]=00000000 00000001 00000001 00000000
ext_cpuid[20]=00000000 00000001 00000001 00000000
ext_cpuid[21]=00000000 00000001 00000001 00000000
ext_cpuid[22]=00000000 00000001 00000001 00000000
ext_cpuid[23]=00000000 00000001 00000001 00000000
ext_cpuid[24]=00000000 00000001 00000001 00000000
ext_cpuid[25]=00000000 00000001 00000001 00000000
ext_cpuid[26]=00000000 00000001 00000001 00000000
ext_cpuid[27]=00000000 00000001 00000001 00000000
ext_cpuid[28]=00000000 00000001 00000001 00000000
ext_cpuid[29]=00000000 00000001 00000001 00000000
ext_cpuid[30]=00000000 00000001 00000001 00000000
ext_cpuid[31]=00000000 00000001 00000001 00000000
intel_fn4[0]=3c004121 01c0003f 0000003f 00000000
intel_fn4[1]=3c004122 01c0003f 0000003f 00000000
intel_fn4[2]=3c004143 01c0003f 000001ff 00000000
intel_fn4[3]=3c07c163 04c0003f 00004fff 00000006
intel_fn4[4]=00000000 00000000 00000000 00000000
intel_fn4[5]=00000000 00000000 00000000 00000000
intel_fn4[6]=00000000 00000000 00000000 00000000
intel_fn4[7]=00000000 00000000 00000000 00000000
intel_fn11[0]=00000001 00000002 00000100 00000004
intel_fn11[1]=00000005 00000014 00000201 00000004
intel_fn11[2]=00000000 00000000 00000002 00000004
intel_fn11[3]=00000000 00000000 00000003 00000004

**Comment by anrieff** [comment]
Fixed in 1599fd5.
