### ISSUE TITLE
Intel Atom N450 not recognised properly

### ISSUE THREAD

**Issue by eloaders** [anrieff/libcpuid#54]
brand_str  : `Intel(R) Atom(TM) CPU N450   @ 1.66GHz'
code name  : `Unknown Atom'
[report.txt](https://github.com/anrieff/libcpuid/files/430537/report.txt)
[raw.txt](https://github.com/anrieff/libcpuid/files/430536/raw.txt)

**Comment by anrieff** [comment]
Fixed in 3f38efb.
