### ISSUE TITLE
cpuid_tool -help talks about libcpuid.so.11 

### ISSUE THREAD

**Issue by shirishag75** [anrieff/libcpuid#73]
I was trying -

```
┌─[shirish@debian] - [~/games] - [10344]
└─[$] cpuid_tool --help                                                                                                           
cpuid_tool: error while loading shared libraries: libcpuid.so.11: cannot open shared object file: No such file or directory
```
No idea why it is searching still for libcpuid.so.11  :(

**Comment by shirishag75** [comment]
This is because libcpuid11 and libcpuid13 and its directories were still in /debian directory. They need to be removed and updated which I manually did.

**Comment by anrieff** [comment]
It seems you're getting an old cpuid_tool. Try removing/reinstalling all libcpuid-related packages, that should fix it.

**Comment by shirishag75** [comment]
Actually it gave me an idea. I looked at /usr/local/bin/ and sure enough there was a cpuid_tool . For the moment I have removed it, let me see if it gets generated again.

**Comment by shirishag75** [comment]
That fixed it :)
