### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by eloaders** [anrieff/libcpuid#77]
He needs to implement Libcpuid in my program, called I-Nex. I'm asking you to enter a JSON format for the command cpuid_tool --report --all
It is very important for me
For example:
> {
> 	"VENDOR_STR": "AuthenticAMD",
> 	"CPU_CODENAME": "Turion X2 (Tyler/256K)",
> 	"BRAND_STR": "AMD Athlon(tm) 64 X2 Dual-Core Processor TK-53",
> 	"NUM_CORES": "2",
> 	"NUM_LOGICAL_CPUS": "2",
> 	"TOTAL_LOGICAL_CPUS": "2",
> 	"FAMILY": "15",
> 	"MODEL": "8",
> 	"STEPPING": "1",
> 	"EXT_FAMILY": "15",
> 	"EXT_MODEL": "104",
> 	"CPU_CLOCK": "800 MHz",
> 	"CPU_CLOCK_BY_OS": "800 MHz",
> 	"CPU_CLOCK_BY_IC": "1595 MHz",
> 	"CPU_CLOCK_MEASURE": "1700 MHz",
> 	"MARK_TSC": "5005",
> 	"MARK_SYS_CLOCK": "1",
> 			"Flags": {
> 			"1": {
> 					"VALUE": 1 , 
> 					"NAME": "CPU_FEATURE_MMXEXT",
> 					"FEATURE": "mmxext",
> 					"WEBSITE": "http://en.wikipedia.org/wiki/MMX_(instruction_set)",
> 					"HAVEWEBSITE": 1 ,
> 					"DESC": "AMD MMX-extended instructions supported"
> 			},
> 			"2": {
> 					"VALUE": 1 , 
> 					"NAME": "CPU_FEATURE_SSE",
> 					"FEATURE": "sse",
> 					"WEBSITE": "http://en.wikipedia.org/wiki/Streaming_SIMD_Extensions",
> 					"HAVEWEBSITE": 1 ,
> 					"DESC": "Streaming-SIMD Extensions (SSE) supported"
> 			}
> 	},
> 	"L1_DATA_CACHE": "64 KB",
> 	"L1_INSTRUCTION_CACHE": "64 KB",
> 	"L2_CACHE": "256 KB",
> 	"L3_CACHE": "Not found",
> 	"L1_ASSOC": "2-way",
> 	"L2_ASSOC": "16-way",
> 	"L3_ASSOC": "Not found",
> 	"L1_CACHELINE": "64 bytes",
> 	"L2_CACHELINE": "64 bytes",
> 	"L3_CACHELINE": "Not found",
> 	"SSE_SIZE": "64 bits (non-authoritative)"
> }

**Comment by anrieff** [comment]
I can do that, but I don't have a lot of free time right now. Are you sure you can't fetch the separate data fields from `cpuid_tool` directly, it is quite easy. For example:

```
[vesko@tank cpuid_tool]$ ./cpuid_tool --vendorstr --codename --brandstr --cores --logical --total-cpus --family --model --stepping --extfamily --extmodel --clock --clock-os --clock-rdtsc --clock-ic --l1d-cache --l1i-cache --l2-cache --l3-cache --l1d-assoc --l2-assoc --l3-assoc --l1d-cacheline --l2-cacheline --l3-cacheline --sse-size
GenuineIntel
Haswell (Core i7)
Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
4
8
8
6
12
3
6
60
2100
2100
2494
3387
32
32
256
6144
8
8
12
64
64
64
128 (non-authoritative)
```

basically gives you the same data, it only doesn't specify which is which, but I believe you can easily do this yourself :) What each row is printing is strictly defined by the order of command line arguments.

**Comment by eloaders** [comment]
In any case, thank you libcpuid keep in good condition and develop it.
I'll deal then with what I have.
