### ISSUE TITLE
Misdiagnosis microarchitecture for i3-3220T

### ISSUE THREAD

**Issue by eloaders** [anrieff/libcpuid#81]
This is Ivy Bridge

`version=0.4.0
basic_cpuid[0]=0000000d 756e6547 6c65746e 49656e69
basic_cpuid[1]=000306a9 03100800 3d9ae3bf bfebfbff
basic_cpuid[2]=76035a01 00f0b2ff 00000000 00ca0000
basic_cpuid[3]=00000000 00000000 00000000 00000000
basic_cpuid[4]=1c004121 01c0003f 0000003f 00000000
basic_cpuid[5]=00000040 00000040 00000003 00001120
basic_cpuid[6]=00000075 00000002 00000009 00000000
basic_cpuid[7]=00000000 00000281 00000000 00000000
basic_cpuid[8]=00000000 00000000 00000000 00000000
basic_cpuid[9]=00000000 00000000 00000000 00000000
basic_cpuid[10]=07300403 00000000 00000000 00000603
basic_cpuid[11]=00000001 00000002 00000100 00000003
basic_cpuid[12]=00000000 00000000 00000000 00000000
basic_cpuid[13]=00000007 00000340 00000340 00000000
basic_cpuid[14]=00000007 00000340 00000340 00000000
basic_cpuid[15]=00000007 00000340 00000340 00000000
basic_cpuid[16]=00000007 00000340 00000340 00000000
basic_cpuid[17]=00000007 00000340 00000340 00000000
basic_cpuid[18]=00000007 00000340 00000340 00000000
basic_cpuid[19]=00000007 00000340 00000340 00000000
basic_cpuid[20]=00000007 00000340 00000340 00000000
basic_cpuid[21]=00000007 00000340 00000340 00000000
basic_cpuid[22]=00000007 00000340 00000340 00000000
basic_cpuid[23]=00000007 00000340 00000340 00000000
basic_cpuid[24]=00000007 00000340 00000340 00000000
basic_cpuid[25]=00000007 00000340 00000340 00000000
basic_cpuid[26]=00000007 00000340 00000340 00000000
basic_cpuid[27]=00000007 00000340 00000340 00000000
basic_cpuid[28]=00000007 00000340 00000340 00000000
basic_cpuid[29]=00000007 00000340 00000340 00000000
basic_cpuid[30]=00000007 00000340 00000340 00000000
basic_cpuid[31]=00000007 00000340 00000340 00000000
ext_cpuid[0]=80000008 00000000 00000000 00000000
ext_cpuid[1]=00000000 00000000 00000001 28100800
ext_cpuid[2]=20202020 49202020 6c65746e 20295228
ext_cpuid[3]=65726f43 294d5428 2d336920 30323233
ext_cpuid[4]=50432054 20402055 30382e32 007a4847
ext_cpuid[5]=00000000 00000000 00000000 00000000
ext_cpuid[6]=00000000 00000000 01006040 00000000
ext_cpuid[7]=00000000 00000000 00000000 00000100
ext_cpuid[8]=00003024 00000000 00000000 00000000
ext_cpuid[9]=00000007 00000340 00000340 00000000
ext_cpuid[10]=00000007 00000340 00000340 00000000
ext_cpuid[11]=00000007 00000340 00000340 00000000
ext_cpuid[12]=00000007 00000340 00000340 00000000
ext_cpuid[13]=00000007 00000340 00000340 00000000
ext_cpuid[14]=00000007 00000340 00000340 00000000
ext_cpuid[15]=00000007 00000340 00000340 00000000
ext_cpuid[16]=00000007 00000340 00000340 00000000
ext_cpuid[17]=00000007 00000340 00000340 00000000
ext_cpuid[18]=00000007 00000340 00000340 00000000
ext_cpuid[19]=00000007 00000340 00000340 00000000
ext_cpuid[20]=00000007 00000340 00000340 00000000
ext_cpuid[21]=00000007 00000340 00000340 00000000
ext_cpuid[22]=00000007 00000340 00000340 00000000
ext_cpuid[23]=00000007 00000340 00000340 00000000
ext_cpuid[24]=00000007 00000340 00000340 00000000
ext_cpuid[25]=00000007 00000340 00000340 00000000
ext_cpuid[26]=00000007 00000340 00000340 00000000
ext_cpuid[27]=00000007 00000340 00000340 00000000
ext_cpuid[28]=00000007 00000340 00000340 00000000
ext_cpuid[29]=00000007 00000340 00000340 00000000
ext_cpuid[30]=00000007 00000340 00000340 00000000
ext_cpuid[31]=00000007 00000340 00000340 00000000
intel_fn4[0]=1c004121 01c0003f 0000003f 00000000
intel_fn4[1]=1c004122 01c0003f 0000003f 00000000
intel_fn4[2]=1c004143 01c0003f 000001ff 00000000
intel_fn4[3]=1c03c163 02c0003f 00000fff 00000006
intel_fn4[4]=00000000 00000000 00000000 00000000
intel_fn4[5]=00000000 00000000 00000000 00000000
intel_fn4[6]=00000000 00000000 00000000 00000000
intel_fn4[7]=00000000 00000000 00000000 00000000
intel_fn11[0]=00000001 00000002 00000100 00000003
intel_fn11[1]=00000004 00000004 00000201 00000003
intel_fn11[2]=00000000 00000000 00000002 00000003
intel_fn11[3]=00000000 00000000 00000003 00000003
intel_fn12h[0]=00000007 00000340 00000340 00000000
intel_fn12h[1]=00000001 00000000 00000000 00000000
intel_fn12h[2]=00000100 00000240 00000000 00000000
intel_fn12h[3]=00000000 00000000 00000000 00000000
intel_fn14h[0]=00000007 00000340 00000340 00000000
intel_fn14h[1]=00000001 00000000 00000000 00000000
intel_fn14h[2]=00000100 00000240 00000000 00000000
intel_fn14h[3]=00000000 00000000 00000000 00000000
CPUID is present
CPU Info:
------------------
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `Intel(R) Core(TM) i3-3220T CPU @ 2.80GHz'
  family     : 6 (06h)
  model      : 10 (0Ah)
  stepping   : 9 (09h)
  ext_family : 6 (06h)
  ext_model  : 58 (3Ah)
  num_cores  : 2
  num_logical: 4
  tot_logical: 4
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 256 KB
  L3 cache   : 3072 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L2 assoc.  : 8-way
  L3 assoc.  : 12-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  SSE units  : 128 bits (non-authoritative)
  code name  : `Sandy Bridge (Core i3)'
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni pclmul dts64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 syscall xd popcnt xsave osxsave avx rdtscp lm lahf_lm constant_tsc f16c
`

**Comment by anrieff** [comment]
Hi!
Thanks for the bug report.
What OS is this run on? Could it be under a VM?
Detection of Ivy bridge relies on the presence of the RdRand instruction. RdRand should be supported on all Ivy Bridge processors, but strangely it is not marked as available on this CPU. This worries me more than the codename misdetection, which can always be worked around.

**Comment by eloaders** [comment]
KUbuntu 16.10

**Comment by anrieff** [comment]
OK, but is this under a VM?
What's the output of `cat /proc/cpuinfo`?

**Comment by eloaders** [comment]
`[michal@michal-pc ~]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x1c
cpu MHz         : 1201.135
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5190.58
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x1c
cpu MHz         : 1200.659
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5192.37
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x1c
cpu MHz         : 1317.773
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5191.92
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x1c
cpu MHz         : 1204.626
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5191.93
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

`

**Comment by anrieff** [comment]
Thanks!
I see that the CPU has RdRand and Linux duly reports it.
Will investigate why libcpuid doesn't detect it.

**Comment by anrieff** [comment]
I added a workaround (commit 86bf8e8), which resolves the issue.
However, before closing this, I want to investigate something else which is strange - your `/proc/cpuinfo` snippet indicates the processor is **Intel(R) Core(TM) i5-3230M**. However, in the libcpuid snapshot the brand string is different - **Intel(R) Core(TM) i3-3220T**. Is it possible that the libcpuid snapshot was obtained on a different machine?

**Comment by eloaders** [comment]
The data are from the same computer

**Comment by anrieff** [comment]
But that doesn't make sense.
OK, for completeness, does the 'brand_str' value from `cpuid_tool` change when you run it in sudo?

**Comment by eloaders** [comment]
i3/i5/i7-2xxx - Sandy
i3/i5/i7-3xxx - ivy
i3/i5/i7-4xxx - Haswell
i3/i5/i7-5xxx - Brodwell
i3/i5/i7-6xxx - Sky lake
i3/i5/i7-7xxx - kabylake

those which have the digital 3: i3 / i5 / i7-xxx - is the first generation

**Comment by anrieff** [comment]
What doesn't make sense is that `/proc/cpuinfo` data and libcpuid data about the brand string are in disagreement. The brand string is obtained through the CPUID instruction. The data from `/proc/cpuinfo`, I believe, is also obtained through CPUID. So the brand strings **must** match exactly - they are obtained from the same place. It is not comforting that both are `i3-3xxx`.

What is even more puzzling is that I believe 3220T is a desktop CPU, whereas 3230M is a mobile one.

**Comment by NetBit73** [comment]
cpuid_tool --all | grep -E "brand|code"
  brand_str  : `Intel(R) Core(TM) i3-3220T CPU @ 2.80GHz'
  code name  : `Sandy Bridge (Core i3)'

but intel says it's Ivy: https://ark.intel.com/pl/products/codename/29902/Ivy-Bridge

**Comment by eloaders** [comment]
I made a mistake giving the wrong cpuinfo. I updated.

**Comment by anrieff** [comment]
Thank you very much. That explains the discrepancy.
The CPU indeed doesn't have RdRand, so it was my error to rely on it being always present. In the end, the fix in commit 86bf8e8 is the right one.
