### ISSUE TITLE
Wrong bus speed and multipliers for AMD Phenom II 940

### ISSUE THREAD

**Issue by kbios** [anrieff/libcpuid#84]
Hey, this is with the git version, so with the RDMSR commits included. With my CPU I'm getting a reported bus speed of 853Mhz (should be a bit more than 200), and a multiplier of x4 (should be 17). Interestingly, before the RDMSR commits I was getting a bus speed of 100 and a multiplier of 34, so it went from one extreme to the other :)
[raw.txt](https://github.com/anrieff/libcpuid/files/818344/raw.txt)
[report.txt](https://github.com/anrieff/libcpuid/files/818345/report.txt)

**Comment by anrieff** [comment]
@X0rg - any ideas?

**Comment by X0rg** [comment]
@kbios: recent changes on RDMSR were to fix that.
With stock clocks, the bus clock should be 200MHz and CPU multiplier x15 (because the stock clock is 3GHz). So yes, this is very buggy. 😢 

Please paste `cpuid_tool --rdmsr` and `cpuid_tool --rdmsr-raw` output.
Your CPU is overclocked at 3,4GHz, right?

**Comment by kbios** [comment]
```
# ./cpuid_tool --rdmsr
  cur. multi.: 1700 MHz
  max. multi.: 1700 MHz
  core volt. : 1.35 Volts
  base clock : 853.75 MHz
# ./cpuid_tool --rdmsr-raw
CPU is AuthenticAMD AMD Phenom(tm) II X4 940 Processor, stock clock is 3415MHz.
msr[0xc0010061]=00 00 00 00 00 00 00 30 
msr[0xc0010063]=00 00 00 00 00 00 00 00 
msr[0xc0010064]=80 00 00 1a 20 00 20 12 
msr[0xc0010065]=80 00 01 c3 30 00 30 07 
msr[0xc0010066]=80 00 01 b6 40 00 40 02 
msr[0xc0010067]=80 00 01 72 40 00 40 40 
msr[0xc0010068]=00 00 01 72 40 00 40 40 
msr[0xc0010069]=00 00 01 72 40 00 40 40 
msr[0xc001006a]=00 00 01 72 40 00 40 40 
msr[0xc001006b]=00 00 01 72 40 00 40 40
```
Exactly, I overclocked to 3.4 by setting the multiplier to 17

**Comment by X0rg** [comment]
Ok, I'm working of this. With my local changes, the computed bus clock is 200,88MHz.
I'll push a fix in a few moment. This issue is related to used method to determine how many Pstate are presents.

**Comment by anrieff** [comment]
Thanks for fixing this, @X0rg!

**Comment by X0rg** [comment]
@kbios: if you can, please update libcpuid to latest git revision and re-paste the `cpuid_tool --rdmsr` output to confirm fix.

@anrieff: NP. I'm now watching libcpuid, I will be notified of all conversations, I think it will be helpful for future issues related to MSRs. ;)

**Comment by kbios** [comment]
Wow that was fast! I can confirm that with the latest commit the bus speed is correct:
```
# cpuid_tool --rdmsr
  min. multi.: 0
  cur. multi.: 0
  max. multi.: 0
  core volt. : 1.35 Volts
  bus clock  : 200.88 MHz
```

**Comment by X0rg** [comment]
And it shows another bug with CPU multipliers...

**Comment by X0rg** [comment]
Maybe the `%d` format, can be replaced by a `%.2f`. Interesting bug.
