### ISSUE TITLE
AMD Ryzen support

### ISSUE THREAD

**Issue by X0rg** [anrieff/libcpuid#86]
AMD Ryzen (Summit Ridge) is now available on AM4 socket!

![CPU-Z screenshot](http://cdn.wccftech.com/wp-content/uploads/2017/03/AMD-Ryzen-7-1800X-Review_CPUz.png)

I think libcpuid need some work to support these new CPUs due to the new architecture:
* [x] Add Ryzen in AMD CPUs DB (`recog_amd.c`)
* [x] Support Ryzen MSRs (`rdmsr.c`)

I think, if you have time, it would be better if you do the first point yourself @anrieff.
Unfortunately, the BKDG the 17h family is still not available.

Ryzen has 2-way SMT, similar to Intel HT technology.

**Comment by anrieff** [comment]
Yup, [here](http://anrieff.net/ucbench/viewitem.php?id=5984)'s a ucbench result I can get the libcpuid raw dump from. I'll do that Monday or Tuesday.

**Comment by X0rg** [comment]
Good new.

I have no idea when AMD will release BKDG for the 17h family.

**Comment by anrieff** [comment]
Detection of codename is done. We can only wait for the BKDG :)

**Comment by X0rg** [comment]
Yes. A lot of people are asking for BKDG on various threads, but still no answer from AMD.
I hope it will be available soon.

**Comment by X0rg** [comment]
Still not BIOS and Kernel Developer’s Guide (BKDG) for AMD Family 17h Models, but there is the [Processor Programming Reference (PPR) for AMD Family 17h](https://support.amd.com/TechDocs/54945_PPR_Family_17h_Models_00h-0Fh.pdf), and page 138 is what I need (CoreCOF, ...).

I will get a look this week, I'm sure `get_amd_multipliers()` need a new case statement.
Any Ryzen MSRs dump?

**Comment by anrieff** [comment]
Yep. Here's one for Ryzen 7:
```
CPU is AuthenticAMD AMD Ryzen 7 1800X Eight-Core Processor         , stock clock is 4002MHz.
msr[0xc0010061]=00 00 00 00 00 00 00 20 
msr[0xc0010063]=00 00 00 00 00 00 00 02 
msr[0xc0010064]=80 00 00 00 49 08 08 78 
msr[0xc0010065]=80 00 00 00 48 08 08 78 
msr[0xc0010066]=80 00 00 00 45 9a 0c 84 
msr[0xc0010067]=00 00 00 00 00 00 00 00 
msr[0xc0010068]=00 00 00 00 00 00 00 00 
msr[0xc0010069]=00 00 00 00 00 00 00 00 
msr[0xc001006a]=00 00 00 00 00 00 00 00 
msr[0xc001006b]=00 00 00 00 00 00 00 00
```

The latest libcpuid decodes this as
```
 MSR.mperf  : 0 MHz
 MSR.aperf  : 0 MHz
 core volt. : 1.47 Volts
```
The actual values (as per CPU-Z) are base clock 133.37, multiplier 30x (CPU frequency is indeed ~4001 MHz), and vcore = 1.308.

The guy who did the tests also has a FX-8320E, where MSR decoding is bogus as well. I'll file a separate issue to track that.

**Comment by X0rg** [comment]
Nice, thank you!
