### ISSUE TITLE
Clang compiler support

### ISSUE THREAD

**Issue by topilski** [anrieff/libcpuid#95]
Hi, please add clang compiler support, bcuz on MacOSX in mostly used clang as compiler. In code you can replace `#if defined(COMPILER_GCC) to #if defined(COMPILER_GCC) || defined(COMPILER_CLANG)` and this should work, also need to detect is compiler clang.

**Comment by anrieff** [comment]
Your fork already has it, right? In lieu of issue #96, I might just integrate that.

**Comment by orivej** [comment]
This might have been fixed by #112. (For me even libcpuid 0.4.0 builds on Linux and macOS with Clang, but I'm using stock Clang that defines `__GNUC__`, not Apple Clang.)

**Comment by anrieff** [comment]
Yes, I can confirm that libcpuid now compiles fine with clang 3.7.0 on Linux. Please report further issues.

**Comment by anrieff** [comment]
And, of course, thanks for your contribution, @orivej :)
