### ISSUE TITLE
Wrong total number of logical cpus on Xeon E3-1240

### ISSUE THREAD

**Issue by NmxMilk** [anrieff/libcpuid#99]
Hi,
Can you please explain why data.total_logical_cpus is returning a value of 4 instead of 8 ?

CPU Info:
------------------
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `Intel(R) Xeon(R) CPU E31240 @ 3.30GHz'
  family     : 6 (06h)
  model      : 10 (0Ah)
  stepping   : 7 (07h)
  ext_family : 6 (06h)
  ext_model  : 42 (2Ah)
  num_cores  : 4
  num_logical: 8
  tot_logical: 4
...
For information, i ran the cpuid_tool under Windows 10.
Windows task manager is giving the following info:
- sockets = 1
- cores = 4
- logical processors = 4

Looking in the source code i see the value is taken (under windows) from GetSystemInfo so that explains the value of 4. This is confusing since intel documentation says it has 8 thread.
 
Thanks

**Comment by anrieff** [comment]
No, in this case `GetSystemInfo()` should return 8, not 4, if the system is configured correctly. It could be that hyper-threading is disabled in BIOS or some setting in the Windows 10 itself (I've never used Windows 10 personally, so I don't know where this can be set/configured). Please also try with CPU-Z and see what it reports.

**Comment by anrieff** [comment]
Closing as old, and no additional data was given to confirm the bug
